import { supabase } from "./supabase";

export const STORAGE_BUCKET = "ticket-adjuntos";

export const STORAGE_SETUP_SQL = `
insert into storage.buckets (id, name, public)
values ('ticket-adjuntos', 'ticket-adjuntos', true)
on conflict (id) do nothing;

create table if not exists public.adjuntos (
  id bigint generated by default as identity primary key,
  ticket_id uuid not null,
  nombre text not null,
  path text not null,
  url text not null,
  tipo text,
  size bigint,
  usuario text,
  created_at timestamptz not null default now()
);

create index if not exists adjuntos_ticket_id_idx on public.adjuntos(ticket_id);
`;

function normalizeTicketId(ticketId) {
    if (!ticketId) {
        throw new Error("ticketId es requerido para gestionar adjuntos.");
    }

    return String(ticketId);
}

function sanitizeFileName(fileName) {
    return fileName
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
        .replace(/[^a-zA-Z0-9.-]+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "")
        .toLowerCase();
}

function buildStoragePath(ticketId, fileName) {
    const extension = fileName.includes(".")
        ? fileName.split(".").pop()
        : "bin";

    const baseName = fileName.replace(/\.[^.]+$/, "") || "archivo";
    const safeName = sanitizeFileName(baseName);
    const uniqueSuffix = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

    return `tickets/${ticketId}/${safeName}-${uniqueSuffix}.${extension.toLowerCase()}`;
}

export async function subirAdjuntoTicket({ ticketId, file, usuario }) {
    const normalizedTicketId = normalizeTicketId(ticketId);
    const path = buildStoragePath(normalizedTicketId, file.name);

    const { error: uploadError } = await supabase.storage
        .from(STORAGE_BUCKET)
        .upload(path, file, {
            cacheControl: "3600",
            upsert: false,
            contentType: file.type || "application/octet-stream",
        });

    if (uploadError) {
        throw uploadError;
    }

    const { data: publicData } = supabase.storage
        .from(STORAGE_BUCKET)
        .getPublicUrl(path);

    const registro = {
        ticket_id: normalizedTicketId,
        nombre: file.name,
        path,
        url: publicData.publicUrl,
        tipo: file.type || "application/octet-stream",
        size: file.size,
        usuario: usuario?.email || usuario || "Sistema",
    };

    const { data, error } = await supabase
        .from("adjuntos")
        .insert([registro])
        .select("*")
        .single();

    if (error) {
        await supabase.storage.from(STORAGE_BUCKET).remove([path]);
        throw error;
    }

    return data;
}

export async function obtenerAdjuntosTicket(ticketId) {
    const normalizedTicketId = normalizeTicketId(ticketId);

    const { data, error } = await supabase
        .from("adjuntos")
        .select("*")
        .eq("ticket_id", normalizedTicketId)
        .order("created_at", { ascending: false });

    if (error) {
        throw error;
    }

    return data || [];
}

export async function obtenerUrlDescarga(path) {
    const { data, error } = await supabase.storage
        .from(STORAGE_BUCKET)
        .createSignedUrl(path, 60);

    if (error) {
        throw error;
    }

    return data.signedUrl;
}

export async function eliminarAdjuntoTicket(adjuntoId, path) {
    const { error: deleteRowError } = await supabase
        .from("adjuntos")
        .delete()
        .eq("id", adjuntoId);

    if (deleteRowError) {
        throw deleteRowError;
    }

    const { error: deleteFileError } = await supabase.storage
        .from(STORAGE_BUCKET)
        .remove([path]);

    if (deleteFileError) {
        throw deleteFileError;
    }
}
