services:
  - type: web
    name: soporte-phidias-api
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_ORIGINS
        sync: false
